pipeline {
    agent { node {label "node-1" } }

    environment { JAG= 'DEVOPS ENGINEER'
    }

    stages {
        stage('code') {
            steps {
                echo 'JAG'
            }
        }
        stage('build') {
            steps {
                echo 'JAG'
            }
        }
        stage('test') {
            steps {
                echo 'JAG'
            }
        }
        stage('code quality') {
            steps {
                echo 'Hello World'
            }
        }
        stage('code security-release') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Deploy-3') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
